### ISSUE TITLE
[Not an issue] question about level editor

### ISSUE THREAD

**Issue by valina354** [TheOverfloater/pathos-public#21]
so i understand that current custom level editor cant be opensourced due to based on 2003 leak, and as fix to that its aimed for trenchboom to be made to work with pathos, but instead has it been explored adding pathos support to sledge (https://developer.valvesoftware.com/wiki/Sledge)? it doesnt seem based on any leaks and seems closest to jack level editor/hammer, or has it not been explored due to being based on  C# and not C++ making it more complex?

**Comment by valina354** [comment]
oh also related to jack according to its page it supports plugins that could add new model format which at least from what i saw is main reason because model format in pathos is different, has this been tried or is there like no documentation anywhere on how to do plugins like that in jack
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/5bcc7b1b-6396-4540-bb0e-3593a7aa636c)

**Comment by TheOverfloater** [comment]
Sledge is the most likely candidate for now, because TrenchBroom is lacking RMF support and MAP alone does not suffice in my opinion. Currently this is on hold however until further notice due to personal reasons. For now it's best to use JACK and just make sure to include geometry data in the HL1 MDL. JACK was also considered but AFAIK there's no documentation on the plugin system.

**Comment by valina354** [comment]
ok, theres also a sledge fork called hammer time https://github.com/Duude92/hammertime that is probably less buggy and has more features so if its ever tried to add pathos support thats probably best choice
