### ISSUE TITLE
Suggestion: a global depth buffer of scene

### ISSUE THREAD

**Issue by valina354** [TheOverfloater/pathos-public#23]
a global depth buffer of scene that has both bsp and vbm stuff would be nice for shaders, i have tried to do it myself using this but for no explainable reason after few sec ingame it crashes my entire gpu and with out its fine im not really sure why, i placed to init it in drawfinal
![image](https://github.com/TheOverfloater/pathos-public/assets/80889633/069ef51c-f688-4644-b264-8ae9e3daa179)

**Comment by TheOverfloater** [comment]
Because Pathos uses Framebuffer Objects for rendering sub-passes, this is only viable for drawing the main screen, and it might explain the crash you are experiencing. Also it depends really on what you want to use it for, because just adding it on it's own without a concrete use case would be eating up VRAM needlessly.

**Comment by valina354** [comment]
im pretty much trying to make like depth of field,ssao shaders and other stuff and they all require depth buffer pretty much
